name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      cpp: ${{ steps.filter.outputs.cpp }}
      golang: ${{ steps.filter.outputs.golang }}
      csharp: ${{ steps.filter.outputs.csharp }}
      php: ${{ steps.filter.outputs.php }}
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            java:
              - 'java/**'
            cpp:
              - 'cpp/**'
            golang:
              - 'golang/**'
            csharp:
              - 'csharp/**'
            php:
              - 'php/**'
            rust:
              - 'rust/**'
  java-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.java == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  cpp-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.cpp == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  csharp-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.csharp == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  golang-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.golang == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  php-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.php == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  rust-build:
    needs: paths-filter
    if: needs.paths-filter.outputs.rust == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Call Java Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: java_build.yml
          ref: ${{ github.event.pull_request.head.ref }}
  build-result:
    runs-on: ubuntu-latest
    needs: [java-build, cpp-build, csharp-build, golang-build, php-build, rust-build]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - name: Collect build result
        run: |
          if echo java-${{ needs.java-build.result }},cpp-${{ needs.cpp-build.result }},csharp-${{ needs.csharp-build.result }},golang-${{ needs.golang-build.result }},php-${{ needs.php-build.result }},rust-${{ needs.rust-build.result }} | grep -E 'cancelled|failure' -o > null
          then
            echo "There are failed/cancelled builds"
            exit 1 
          else
            echo "All builds are successful/skipped"
            exit 0
          fi
