name: Java Build
on: 
  workflow_call:
jobs:
  build:
    name: "${{ matrix.os }}, jdk-${{ matrix.jdk }}, ${{ matrix.vm }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
        jdk: [11, 17]
        vm: [hotpot, openj9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.vm == 'hotspot' && 'adopt' || 'adopt-openj9'}}
          cache: maven
      - name: Build with Maven
        working-directory: ./java
        run: mvn -B package --file pom.xml
